CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(50) NOT NULL,
  lastName VARCHAR(50) NOT NULL,
  username VARCHAR(20) NOT NULL,
  userPassword VARCHAR(200) NOT NULL,
  email VARCHAR(100) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (username),
  UNIQUE KEY (email)
);

CREATE TABLE post (
  postID INT NOT NULL AUTO_INCREMENT,
  postText VARCHAR(200),
  userID INT NOT NULL,
  timeEditedOrCreated TIMESTAMP NOT NULL,
  likes INT NOT NULL,
  FOREIGN KEY (userID) REFERENCES user(id),
  PRIMARY KEY (id)
);